[workspace]
members = ["crates/core", "crates/cli", "crates/gui"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
clap = { version = "4.6.4", features = ["derive"] }
quick-xml = { version = "0.41.0", features = ["serialize"] }
serde = { version = "1.0.229", features = ["derive"] }
tree-sitter = "0.26.11"
tree-sitter-java = "0.23.5"
criterion = "0.5"
